### ISSUE TITLE
Missing faceverse_v3.npy

### ISSUE THREAD

**Issue by hcl14** [MrTornado24/Next3D#13]
For `Next3D/dataset_preprocessing/ffhq/faceverse/fit_imgs_offline_cuda.py` I need `data/faceverse_v3.npy`. Original faceverse repo provides only v1 and v2, and I can't feed them instead, because it does not have "madiapipe_keypoints":

```
self.kp_inds = jt.array(model_dict['mediapipe_keypoints'].flatten(), dtype=jt.int64).stop_grad()
```

**Comment by aistudio2002** [comment]
hi, I'm facing the same problem, wuould you like to tell me where to download data/faceverse_v3.npy, thank you in advance.

**Comment by MrTornado24** [comment]
@aistudio2002 Hi, here it is: [https://drive.google.com/file/d/1Z3aVqNc6yHY0AAmY6IaD36CzkE6tLf_D/view?usp=sharing](url).
 Let me know if it works for you.

**Comment by aistudio2002** [comment]
It helps a lot! Though I've found another link in Readme, this one would be helpful to other readers.
