### ISSUE TITLE
Issue of reload_modules

### ISSUE THREAD

**Issue by zxYin** [MrTornado24/Next3D#15]
Hi,

I have been trying to use the generator `TriPlaneGenerator`. When loading it with `legacy`, everything is fine. However,  I am experiencing some issues when reloading the network pickle into it by using   `copy_params_and_buffers` , as shown in the demo code. I have noticed some artifacts when doing so, which are visible in the following image:

<img width="1015" alt="1" src="https://user-images.githubusercontent.com/33487417/231722956-07803f3c-c48a-4498-ba1c-461e76a87893.png">

I also came across what seems to be a bug in the code at this location: 
https://github.com/MrTornado24/Next3D/blob/bdab84fc12cb61bd1002a3efb2c0a707a1139d97/training_avatar_texture/triplane_next3d.py#L226

 I would appreciate any insights or assistance you could provide to help me resolve this issue.

Thank you for your time and support. I look forward to your response.

**Comment by Piurvus** [comment]
Hey, I had the same issues. It seems as if their code is somewhat faulty.
However, thanks to Nvidias persistence class you can get their previous code.
```G['G_ema']._orig_module_src```

**Comment by RaymondJiangkw** [comment]
Hi, you can see [this](https://github.com/MrTornado24/Next3D/issues/7#issuecomment-1474619770). 👀

**Comment by zxYin** [comment]
Thanks for your help
