### ISSUE TITLE
The code generates a tensor with empty UV (ultraviolet) data.

### ISSUE THREAD

**Issue by wenxinyuan** [MrTornado24/Next3D#30]
![Snipaste_2023-09-20_22-00-45](https://github.com/MrTornado24/Next3D/assets/48885367/4b18b07a-84b8-4aa0-91e1-ea022fe7c55c)
The error code is as shown above. Does anyone have any solutions?

**Comment by n-w-a** [comment]
@wenxinyuan hello! I had the same problem. How did you solve it? Or could you give me some advice? Thank you!
