### ISSUE TITLE
关于one-shot facial avatars和eg3d-pti的问题，请问是需要先对eg3d的预训练模型进行pti还是对训练好的next3d模型进行pti

### ISSUE THREAD

**Issue by aurelianocyp** [MrTornado24/Next3D#38]
同学您好，我在尝试使用eg3d-pti的代码对next3d的模型进行pti，但是会报一些错，我目前遇到的错是
`  File "/root/autodl-tmp/Next3D/eg3d/torch_utils/misc.py", line 97, in assert_shape
    raise AssertionError(f'Wrong size for dimension {idx}: got {size}, expected {ref_size}')
AssertionError: Wrong size for dimension 1: got 28, expected 14`
所以我不清楚是需要先对eg3d的预训练模型进行pti然后训练新的next3d还是对训练好的next3d模型进行pti，如果是可以对next3d模型进行pti的话，可否麻烦您给一些如何修改eg3d-pti项目中代码的指示，感激不尽！

**Comment by MrTornado24** [comment]
你好，关于对next3d进行pti, 流程应该是直接对训练好的next3d进行pti. 你可以参考https://cloud.tsinghua.edu.cn/f/fecfe21668be40bb91a2/?dl=1

**Comment by aurelianocyp** [comment]
谢谢您的code，我微调成功了
