### ISSUE TITLE
Will you release the Code?

### ISSUE THREAD

**Issue by tlok666** [MrTornado24/Next3D#5]
Hi, thanks for this interesting work. I read your paper and find it interesting.

This repo was created a few moths ago but no update during this period. Will you have any plan to release the code?

**Comment by 87003697** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ForrestPi** [comment]
@87003697 waiting to release the code

**Comment by MrTornado24** [comment]
Hi, thanks for your interest in our work! We will release the code as soon as possible.
