### ISSUE TITLE
About re-render the template mesh for Discriminator

### ISSUE THREAD

**Issue by Talegqz** [MrTornado24/Next3D#6]
Thanks for your excellent work.

In the paper, you said that "we re-render the template mesh under the rendered pose to get the synthetic rendering Isynthetic and feed it into Ddual along with image pairs".

However, I am having difficulty locating this specific process within the repository. 
Could you please provide more information about how this process is implemented or direct me to a resource that explains it more clearly? 

Thanks for your help!

**Comment by MrTornado24** [comment]
Hi, as we mentioned in README.md, re-rendering will slow down the training speed so we currently don't release the part. We are trying to re-implement it faster.

**Comment by Talegqz** [comment]
I see. Thanks for your reply.
