### ISSUE TITLE
Missing data/ffhq/head_template.obj

### ISSUE THREAD

**Issue by sunshineatnoon** [MrTornado24/Next3D#7]
Hi, Thanks for open-sourcing the code! 

I'm trying to run the demo with `reload_modules=True` such that I can follow each step in the code. But I encountered the following error `FileNotFoundError: [Errno 2] No such file or directory: 'data/ffhq/head_template.obj'`. Could you please upload the missing obj file? Thanks!

**Comment by RaymondJiangkw** [comment]
I think the 'head_template.obj' could be downloaded from [here](https://github.com/yfeng95/DECA/tree/master/data).

Alternatively, you could comment out all the relevant codes about reading some missing files and doing certain calculations, and simply copy the processed data from the pretrained checkpoint into your reloaded module. It works fine.

**Comment by jingyang2017** [comment]
Hi, Thanks for the code. I met another problem when I set  reload_modules=True.
/pytorch3d/pytorch3d/io/obj_io.py:548: UserWarning: Mtl file does not exist: data/ffhq/template.mtl warnings.warn(f"Mtl file does not exist: {f}"). The warning caused broken face in generation.

**Comment by RaymondJiangkw** [comment]
Hi, I think you can try to replace the L171-172 of 'triplane_next3d.py' with following codes:

```python
alpha_image = torch.cat((alpha_images[0], torch.zeros_like(alpha_images[0]), torch.zeros_like(alpha_images[0])), 1).unsqueeze(2)
rendering_stitch = torch.cat((rendering_stitch, torch.zeros_like(rendering_images[1]), torch.zeros_like(rendering_images[2])), 1)
```

It may work.

**Comment by jingyang2017** [comment]
Thanks!

**Comment by sunshineatnoon** [comment]
Thanks for the quick reply!
